global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'threat-intel'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']