name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build and push to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
          docker build -t threat-intel .
          docker tag threat-intel:latest ${{ secrets.ECR_REGISTRY }}/threat-intel:latest
          docker push ${{ secrets.ECR_REGISTRY }}/threat-intel:latest
      - name: Deploy to ECS
        run: aws ecs update-service --cluster threat-intel --service threat-intel-service --force-new-deployment